### PR TITLE
nib plugin addition in es6 style

### PR DESCRIPTION
**Pull request by simrobin**
Hello !

Here it is ! Now available with the es6 package syntax.
Nib will provide awesome cross-browser mixins to the package, if the user activate it.

### CODE REVIEW

**Comment by olmokramer** [comment]
Awesome! Thank you very much, I'll try it myself and publish a new version if it works

**Comment by olmokramer** [comment]
Works great! :fireworks: New version 0.3.0 is up. Thanks again!

**Comment by olmokramer** [comment]
I've never really looked at the Nib library by the way, but some of the features look really great!

**Comment by simrobin** [comment]
Nice ! Thank you.
Yes, the extension is just great when you don't want to care about vendor prefixes in your stylesheets.

**Comment by olmokramer** [comment]
Hi @simrobin,

v0.6.0 has changed how libraries are included in the compilation process, as requested in #11. As of now, the `nib` toggle isn't available anymore, but instead you can include multiple libraries. So this is just a heads up that the update will probably break some of your configs. If this is really inconvenient for you (e.g. because you have a few 100 files that depend on this feature) please let me know and I can add the setting back, but I'd rather not have you depend on the version of `nib` that comes bundled with this package :)

The following code demonstrates the new way to include `nib` in your project:

``` stylus
// out: style.css, libs: nib

@import "nib";

// ... code using the nib library
```

is equivalent to the old

``` stylus
// out: style.css, nib: true

// ... code using the nib library
```

**Comment by simrobin** [comment]
Hi @olmokramer,

That's a great improvement for the package! 
Thank you very much for keeping me advised :). 
I'll make the needed adjustments in my projects, no need to add a custom setting for me ;)!

**Comment by olmokramer** [comment]
Glad you like it :) Good luck with the upgrading process!

**Pull request merged**
